### PR TITLE
September 2022 Update

### PR DESCRIPTION
**Pull request by maciejpedzich**
@mackorone, Netlify should create a preview deploy in a minute. Could you take a look and see if I should tweak anything?

### CODE REVIEW

**Comment by maciejpedzich** [comment]
> @mackorone, Netlify should create a preview deploy in a minute. Could you take a look and see if I should tweak anything?

Hmm... that's odd. Something went wrong while creating a production build, and it appears to have something to do with the charts library. Give me a sec.

**Comment by maciejpedzich** [comment]
> > @mackorone, Netlify should create a preview deploy in a minute. Could you take a look and see if I should tweak anything?
> 
> Hmm... that's odd. Something went wrong while creating a production build, and it appears to have something to do with the charts library. Give me a sec.

I've resolved the issue. The preview link is above!

**Comment by mackorone** [comment]
> if I should tweak anything

The "Export to JSON" button looks and works great! Were you also planning on adding a "Copy playlist URLs" button? I think it'd be really useful for non-technical folks who want to re-create old versions of their favorite playlists (see my original comment on https://github.com/mackorone/spotify-playlist-archive/issues/134)

**Comment by maciejpedzich** [comment]
> > if I should tweak anything
> 
> Were you also planning on adding a "Copy playlist URLs" button?

Yeah, it should be right next to the Export button... but if you couldn't see it, I believe I know why. Give me a minute and I'll push an update. Also, there's the _Get playlist ID from URL_ page too, so feel free to check it out as well!

**Comment by maciejpedzich** [comment]
@mackorone so previously I showed the copy button only if the browser supported the Clipboard API and permission to write to clipboard was granted. Now instead of hiding the button, the site just disables it and places an info icon to its left. When hovered over, it explains why you can't use the feature.

If the Clipboard API is not supported:
Clipboard API unsupported popup

If writing to clipboard is not allowed:
Writing to clipboard is not allowed popup

**Comment by mackorone** [comment]
> the site just disables it and places an info icon to its left

Ah, got it. Thanks for clarifying. I just tested the "Copy track URLs" button with a browser that supports it - it works great! That said, I wonder if there's something we can do for the other browsers... perhaps in that case, the button can instead just open a page containing *only* the URLs, so that the user can select them manually? Something like GitHub's "Raw" button that displays when browsing files?

> Also, there's the Get playlist ID from URL page too

Just played around with this - works great!

**Comment by maciejpedzich** [comment]
> I wonder if there's something we can do for the other browsers... perhaps in that case, the button can instead just open a page containing _only_ the URLs, so that the user can select them manually? Something like GitHub's "Raw" button that displays when browsing files?


That's a great idea! Funnily enough, I implemented something similar for the _Get playlist's ID_ page, where the copy button falls back to showing the ID for user to copy manually.

image

**Comment by maciejpedzich** [comment]
Yo @mackorone, right when I was about to push the commit with fallback dialog for copying track URLs, I realised I had 5 minutes to catch my bus to school. I didn't miss it in the end, but I didn't push the changes, so you will have to wait 7 or so hours before I get back home

**Comment by maciejpedzich** [comment]
Hey @mackorone, sorry about the seven-hour wait! I've just come back home and pushed all commits. Now if you want to copy a snapshot's track URLs, but the clipboard is unavailable, an appropriate dialog will show up.

Dialog with track URLs to copy

**Comment by mackorone** [comment]
Looks great!

**Comment by maciejpedzich** [comment]
> Looks great!

Gotcha! I'm on my way home as we speak, will let you know once I've merged the PR and all the changes are live.

**Pull request merged**
